<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fund extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fund_model');
    } 

    /*
     * Listing of fund
     */
    function index()
    {
        $data['fund'] = $this->Fund_model->get_all_fund();
        
        $data['_view'] = 'fund/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fund
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'UserId' => $this->input->post('UserId'),
				'Invenstment' => $this->input->post('Invenstment'),
				'Invenstment_Date' => $this->input->post('Invenstment_Date'),
				'Invenstment_Status' => $this->input->post('Invenstment_Status'),
				'Withdraw' => $this->input->post('Withdraw'),
				'Withdraw_Date' => $this->input->post('Withdraw_Date'),
				'Withdraw_Status' => $this->input->post('Withdraw_Status'),
            );
            
            $fund_id = $this->Fund_model->add_fund($params);
            redirect('fund/index');
        }
        else
        {            
            $data['_view'] = 'fund/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fund
     */
    function edit($Id)
    {   
        // check if the fund exists before trying to edit it
        $data['fund'] = $this->Fund_model->get_fund($Id);
        
        if(isset($data['fund']['Id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'UserId' => $this->input->post('UserId'),
					'Invenstment' => $this->input->post('Invenstment'),
					'Invenstment_Date' => $this->input->post('Invenstment_Date'),
					'Invenstment_Status' => $this->input->post('Invenstment_Status'),
					'Withdraw' => $this->input->post('Withdraw'),
					'Withdraw_Date' => $this->input->post('Withdraw_Date'),
					'Withdraw_Status' => $this->input->post('Withdraw_Status'),
                );

                $this->Fund_model->update_fund($Id,$params);            
                redirect('fund/index');
            }
            else
            {
                $data['_view'] = 'fund/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fund you are trying to edit does not exist.');
    } 

    /*
     * Deleting fund
     */
    function remove($Id)
    {
        $fund = $this->Fund_model->get_fund($Id);

        // check if the fund exists before trying to delete it
        if(isset($fund['Id']))
        {
            $this->Fund_model->delete_fund($Id);
            redirect('fund/index');
        }
        else
            show_error('The fund you are trying to delete does not exist.');
    }
    
}
