<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_personal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_personal_model');
    } 

    /*
     * Listing of user_personal
     */
    function index()
    {
        $data['user_personal'] = $this->User_personal_model->get_all_user_personal();
        
        $data['_view'] = 'user_personal/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_personal
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'UserId' => $this->input->post('UserId'),
				'Name' => $this->input->post('Name'),
				'TCNo' => $this->input->post('TCNo'),
				'Password' => $this->input->post('Password'),
				'Active' => $this->input->post('Active'),
            );
            
            $user_personal_id = $this->User_personal_model->add_user_personal($params);
            redirect('user_personal/index');
        }
        else
        {            
            $data['_view'] = 'user_personal/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_personal
     */
    function edit($Id)
    {   
        // check if the user_personal exists before trying to edit it
        $data['user_personal'] = $this->User_personal_model->get_user_personal($Id);
        
        if(isset($data['user_personal']['Id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'UserId' => $this->input->post('UserId'),
					'Name' => $this->input->post('Name'),
					'TCNo' => $this->input->post('TCNo'),
					'Password' => $this->input->post('Password'),
					'Active' => $this->input->post('Active'),
                );

                $this->User_personal_model->update_user_personal($Id,$params);            
                redirect('user_personal/index');
            }
            else
            {
                $data['_view'] = 'user_personal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_personal you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_personal
     */
    function remove($Id)
    {
        $user_personal = $this->User_personal_model->get_user_personal($Id);

        // check if the user_personal exists before trying to delete it
        if(isset($user_personal['Id']))
        {
            $this->User_personal_model->delete_user_personal($Id);
            redirect('user_personal/index');
        }
        else
            show_error('The user_personal you are trying to delete does not exist.');
    }
    
}
