<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_company_model');
    } 

    /*
     * Listing of user_company
     */
    function index()
    {
        $data['user_company'] = $this->User_company_model->get_all_user_company();
        
        $data['_view'] = 'user_company/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_company
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'UserId' => $this->input->post('UserId'),
				'Name' => $this->input->post('Name'),
				'VKNo' => $this->input->post('VKNo'),
				'Password' => $this->input->post('Password'),
				'Active' => $this->input->post('Active'),
            );
            
            $user_company_id = $this->User_company_model->add_user_company($params);
            redirect('user_company/index');
        }
        else
        {            
            $data['_view'] = 'user_company/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_company
     */
    function edit($Id)
    {   
        // check if the user_company exists before trying to edit it
        $data['user_company'] = $this->User_company_model->get_user_company($Id);
        
        if(isset($data['user_company']['Id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'UserId' => $this->input->post('UserId'),
					'Name' => $this->input->post('Name'),
					'VKNo' => $this->input->post('VKNo'),
					'Password' => $this->input->post('Password'),
					'Active' => $this->input->post('Active'),
                );

                $this->User_company_model->update_user_company($Id,$params);            
                redirect('user_company/index');
            }
            else
            {
                $data['_view'] = 'user_company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_company you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_company
     */
    function remove($Id)
    {
        $user_company = $this->User_company_model->get_user_company($Id);

        // check if the user_company exists before trying to delete it
        if(isset($user_company['Id']))
        {
            $this->User_company_model->delete_user_company($Id);
            redirect('user_company/index');
        }
        else
            show_error('The user_company you are trying to delete does not exist.');
    }
    
}
