<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fund_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fund by Id
     */
    function get_fund($Id)
    {
        return $this->db->get_where('fund',array('Id'=>$Id))->row_array();
    }
        
    /*
     * Get all fund
     */
    function get_all_fund()
    {
        $this->db->order_by('Id', 'desc');
        return $this->db->get('fund')->result_array();
    }
        
    /*
     * function to add new fund
     */
    function add_fund($params)
    {
        $this->db->insert('fund',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fund
     */
    function update_fund($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('fund',$params);
    }
    
    /*
     * function to delete fund
     */
    function delete_fund($Id)
    {
        return $this->db->delete('fund',array('Id'=>$Id));
    }
}
