<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get role by Id
     */
    function get_role($Id)
    {
        return $this->db->get_where('roles',array('Id'=>$Id))->row_array();
    }
        
    /*
     * Get all roles
     */
    function get_all_roles()
    {
        $this->db->order_by('Id', 'desc');
        return $this->db->get('roles')->result_array();
    }
        
    /*
     * function to add new role
     */
    function add_role($params)
    {
        $this->db->insert('roles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update role
     */
    function update_role($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('roles',$params);
    }
    
    /*
     * function to delete role
     */
    function delete_role($Id)
    {
        return $this->db->delete('roles',array('Id'=>$Id));
    }
}
