<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_company by Id
     */
    function get_user_company($Id)
    {
        return $this->db->get_where('user_company',array('Id'=>$Id))->row_array();
    }
        
    /*
     * Get all user_company
     */
    function get_all_user_company()
    {
        $this->db->order_by('Id', 'desc');
        return $this->db->get('user_company')->result_array();
    }
        
    /*
     * function to add new user_company
     */
    function add_user_company($params)
    {
        $this->db->insert('user_company',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_company
     */
    function update_user_company($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('user_company',$params);
    }
    
    /*
     * function to delete user_company
     */
    function delete_user_company($Id)
    {
        return $this->db->delete('user_company',array('Id'=>$Id));
    }
}
