<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_personal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_personal by Id
     */
    function get_user_personal($Id)
    {
        return $this->db->get_where('user_personal',array('Id'=>$Id))->row_array();
    }
        
    /*
     * Get all user_personal
     */
    function get_all_user_personal()
    {
        $this->db->order_by('Id', 'desc');
        return $this->db->get('user_personal')->result_array();
    }
        
    /*
     * function to add new user_personal
     */
    function add_user_personal($params)
    {
        $this->db->insert('user_personal',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_personal
     */
    function update_user_personal($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('user_personal',$params);
    }
    
    /*
     * function to delete user_personal
     */
    function delete_user_personal($Id)
    {
        return $this->db->delete('user_personal',array('Id'=>$Id));
    }
}
